### ISSUE TITLE
React’s powerful composition link in "React Router in React" chapter doesn't work

### ISSUE THREAD

**Issue by pantonie** [the-road-to-react-with-firebase/the-road-to-react-with-firebase#5]
Hi,
I'm reading book and noticed "React’s powerful composition" link in "React Router in React" chapter doesn't work. Seems there should be some article on your site but there is 404 error instead.
![404 page not found - rwieruch - google chrome 2019-01-30 11 45 38](https://user-images.githubusercontent.com/18538231/51969296-1bf80480-2485-11e9-909b-9ed37227e7e2.png)

**Comment by rwieruch** [comment]
Hi Anton. Yes, you are too fast :D The article is not published on my website yet.
